language: python

python:
    - "3.5"
    - "3.6"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pandas pytest requests h5py
  - wget https://github.com/nasedil/python-opc/archive/master.zip -O python-opc.zip;
  - unzip python-opc.zip -d $HOME/python-opc
  - source activate test-environment
  - pip install lxml
  - pip install generateDS
  - pip install coverage==3.7.1
  - pip install pytest-cov coveralls
  - cd $HOME/python-opc && python setup.py develop && cd -
  - python setup.py install

script:
    - py.test --cov=dasprodml

after_success:
    - coveralls

notifications:
  email:
    recipients:
      - bjorn.dissing@bitsort.io
      - yevgheni.petkevich.ziebel@gmail.com
    on_success: change
    on_failure: change

# Use https (public access) instead of git for git-submodules. This modifies only Travis-CI behavior!
# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
